apiVersion: v1
kind: Service
metadata:
  name: {{ include "itt-orchestrator.fullname" . }}-otel
  labels:
    {{- include "itt-orchestrator.labels" . | nindent 4 }}
    component: otel
spec:
  type: ClusterIP
  ports:
  - port: 4317
    targetPort: otlp-grpc
    protocol: TCP
    name: otlp-grpc
  - port: 4318
    targetPort: otlp-http
    protocol: TCP
    name: otlp-http
  - port: 8888
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "itt-orchestrator.selectorLabels" . | nindent 4 }}
    component: otel
